INCDIR = ../

CC = gcc -DPLATFORM_WIN32 -I $(INCDIR) -Wall
AR = ar -ru
RM = del

OBJS    = cmnllib.o

cmnllib.a : $(OBJS) 
	$(AR) cmnllib.a $(OBJS)
	
cmnllib.o: cmnllib.c
	$(CC) -c cmnllib.c -o cmnllib.o

clean :
	$(RM) *.o *.a
	
