CC      = gcc -D__LINUX__ -Wall
OBJS    = crc32.o mbase.o message.o lastread.o subpack.o

jamlib.a : $(OBJS) 
	ar -ru jamlib.a $(OBJS)
	cp jamlib.a ../

crc32.o:    crc32.c jam.h
	$(CC) -c crc32.c -o crc32.o

mbase.o:    mbase.c jam.h
	$(CC) -c mbase.c -o mbase.o

message.o:  message.c jam.h
	$(CC) -c message.c -o message.o

lastread.o: lastread.c jam.h
	$(CC) -c lastread.c -o lastread.o

subpack.o:  subpack.c jam.h
	$(CC) -c subpack.c -o subpack.o
